name: e_commerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dio: ^4.0.6
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.3.0
  flutter_screenutil: ^5.4.0+1
  get: 4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  google_sign_in: ^5.3.0
  logger: ^1.1.0
  badges: ^2.0.2
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.0
  readmore: ^2.1.0
  geolocator: ^8.2.1
  geocoding: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
